[profile.default]
src = "src"
out = "out"
libs = ["dependencies"]
solc_version = "0.8.29"
via-ir = true
remappings = [
    "forge-std/=dependencies/forge-std-1.9.6/src/",
    "@optimism/bedrock/=dependencies/@eth-optimism-contracts-bedrock-0.17.3/src/"
]

[dependencies]
forge-std = "1.9.6"

[rpc_endpoints]
SpokeChain = "http://127.0.0.1:9545/"
HubChain = "http://127.0.0.1:9546/"


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
